name: CI/CD Pipeline
env:
  NAME: 'DEV'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Environment
        run: |
          pac auth create --environment ${{ vars.ENVIRONMENT_ID }} --applicationId ${{ secrets.CLIENT_ID }} --clientSecret ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
      